

%MACRO IDENTIFICA_SEMANA(DATA);
%SYMDEL DT_INI_1 DT_INI_2 DT_INI_3 DT_INI_4 DT_INI_5 
		DT_FIM_1 DT_FIM_2 DT_FIM_3 DT_FIM_4 DT_FIM_5;
%GLOBAL DT_INI_1 DT_INI_2 DT_INI_3 DT_INI_4 DT_INI_5 
		DT_FIM_1 DT_FIM_2 DT_FIM_3 DT_FIM_4 DT_FIM_5;
DATA _NULL_;
	DT_INI = %SYSFUNC(INPUTN(&DATA.01, YYMMDD10.));				/*Transforma em Data do SAS              */
	DT_ULTM_DIA = INTNX('MONTH', DT_INI, 1) - 1;				/*Obtem ultimo dia do Mes                */
	I = 1;
	DO UNTIL(DT_FIM=DT_ULTM_DIA);*i = 1 TO 5;
		SOMA_SEMANA = 11 - MOD(WEEKDAY(DT_INI)+3,7);		    /*Será utilizado para o tamanho da semana*/

		IF SOMA_SEMANA > DT_ULTM_DIA - DT_INI THEN DT_FIM = DT_ULTM_DIA;
		ELSE DT_FIM = DT_INI + SOMA_SEMANA;

		CALL SYMPUT(CATS('DT_INI_',i), PUT(DT_INI,DATE9.));
		CALL SYMPUT(CATS('DT_FIM_',i), PUT(DT_FIM,DATE9.));
		i = i + 1;
		DT_INI = DT_FIM + 1;
	END;
RUN; 

%PUT NOTE: 1ª SEMANA: INICIO = &DT_INI_1. | FIM =  &DT_FIM_1.;
%PUT NOTE: 2ª SEMANA: INICIO = &DT_INI_2. | FIM =  &DT_FIM_2.;
%PUT NOTE: 3ª SEMANA: INICIO = &DT_INI_3. | FIM =  &DT_FIM_3.;
%PUT NOTE: 4ª SEMANA: INICIO = &DT_INI_4. | FIM =  &DT_FIM_4.;
%PUT NOTE: 5ª SEMANA: INICIO = &DT_INI_5. | FIM =  &DT_FIM_5.;
%MEND IDENTIFICA_SEMANA;


/* Exemplos de Uso */
%IDENTIFICA_SEMANA(201905);
%IDENTIFICA_SEMANA(201906);
%IDENTIFICA_SEMANA(201907);
